### ISSUE TITLE
Framework

### ISSUE THREAD

**Issue by okpatil4u** [reddit-india/indianelectionmeter.github.io#1]
Good old bootstrap 3, angularjs and jquery. Does anyone have suggestions ?

**Comment by srinarasi** [comment]
Whatever helps us get off the ground quickly. I'm ok with any technology. I think the most of our effort should be spent in presenting the information in a way which is easily understandable to the user and maintaining the community.

**Comment by okpatil4u** [comment]
That makes sense. I am thinking on storing and retrieving data as simple json files rather than database. It would make our life easier.

**Comment by ndarville** [comment]
Consider using YAML for the datastore instead—and use GitHub Pages’s built-in Jekyll to loop over it (cc #5). It's very readable for non-technical people who want to contribute. Jekyll reads YAML just as well as JSON. You can always move on to another framework, if you want the site to do more.

Here’s an example from a project of mine:
- [YAML](https://github.com/hafniatimes/hafniatimes.github.io/blob/f3d07f42afc1b168a33883427fdae46894bfc58a/data/links/en.yml)
- [Front-end code](https://github.com/hafniatimes/hafniatimes.github.io/blob/3f19a3f1d1ec794bfcf876f4001e64b619510e68/_layouts/frontpage.html#L31-L33) for fetching and displaying

I can do a pull request for a sample page, perhaps today, perhaps next week, but we should decide on what the keys the objects in the datastore should have, such as

``` yaml
- title: foo
  description: bar
  promise: kept
```

Or something like that.

This should be decided in separate issue, though.

If you move the repo to `reddit-india/reddit-india.github.io`, the site will automatically be generated at `reddit-india.github.io`, just like https://ndarville.github.io from https://github.com/ndarville/ndarville.github.io. I also host `hafniatimes` like this via https://github.com/hafniatimes/hafniatimes.github.io, although I just a custom domain and CloudFlare for CDN.

If you host it on reddit-india.github.io, you won’t have to pay a hosting fee, so. :)

**Comment by avinassh** [comment]
Or we can ask [these guys](https://www.trudeaumetre.ca/about) for source code.

**Comment by greyhound291** [comment]
That's what I was wondering.. Maybe try talking to someone who has already done it before.. @avinassh

**Comment by kjaggu** [comment]
Great idea. Why reinvent the wheel? We can obviously give them due credit. Moreover, we can share with them our additions for future development.

**Comment by okpatil4u** [comment]
@avinassh we can always do that, but developing a small informative site should not take too long. @ndarville that makes. @avinassh can you update the links at reddit. It's https://github.com/reddit-india/indianelectionmeter.github.io now.

**Comment by avinassh** [comment]
Links of?

**Comment by okpatil4u** [comment]
@avinassh links at the reddit post. @greyhound291 has updated them. Wrong tag.

**Comment by okpatil4u** [comment]
Jekyll site is online at indianelectionmeter.in. So we have started something off.Jekyll site should be progress indicator for now.
Let's decide on frameworks quickly and get started with it on master branch.

**Comment by avinassh** [comment]
Sent my first PR

btw you own the @redditatindia handle on Twitter?

**Comment by ndarville** [comment]
@okpatil4u Just use `indianelectionmeter`, if you want it as a subsection of `reddit-india`. It’s currently at <https://reddit-india.github.io/indianelectionmeter.github.io/>.

**Comment by greyhound291** [comment]
@okpatil4u @avinassh I got a pm from this guy on reddit who claims the following :

> An year and half ago (early 2014), I came across politifact, and wanted to create a same one for the new Indian government to be formed. I went ahead and bought a domain (netapulse.com) and made a model for how the site should work. I started building the site on and off during the sem break.
> It was turning out fine, but my family thought that the site wouldn't work in India, and that the country had a enormous number of politicians for me cover and keep a track. I tried explaining them that the content would be user generated, but they wouldn't agree.
> I tried roping in my friends but none of them were remotely interested in developing, curating or even maintaining back-end for such a website. And a new semester started and I too didn't feel the website would work in India. So, I left the project incomplete. I was thrilled when I saw this post and people where demanding when such a website be made. So I would totally like to contribute to it.
> I have a model ready, and how to go on about the bigger and smaller problems for designing, collecting and maintaining the website.
> Sadly, I have lost the folders for the website. The hard disk in which I had them was formatted, and the copy in the godaddy was also removed when the one year period for the domain ended. But, I can write the codes again with help from you guys here after my end sems (during winter break).
> We can create a temporarily subreddit for the same, to start collecting the data, and comments which can later be imported to the site by running js and python scripts.
> The website I was developing was based on ruby on rails. If people aren't comfortable with it, I can work on other frameworks too.
> Sorry for the long message, but you can count me in for contributing for the development of the site and to be a part of it.

I have asked him to come on over here but I dont think he has joined... if anyone thinks what he is doing/has done is useful, maybe we could track him down or soemthing

**Comment by okpatil4u** [comment]
Yes. I have changed it to twitter.com/electionmeter. I saw that comment as well. I have told him to create a github repository and comment here. Let's see where it goes.

**Comment by ndarville** [comment]
Alright, I whipped up a VERY quick example of what you can do with Jekyll and basic YAML without any of all the usual crap, drawing on the Canadian example:
- Source: https://github.com/ndarville/goal-tracker/tree/gh-pages
- Demo: https://ndarville.github.io/goal-tracker/

I used skeleton.css as the CSS (framework).

This has been done purely in Liquid templating using the [YAML files](https://github.com/ndarville/goal-tracker/tree/gh-pages/_data/goals) as datastore without any JS magic. I hope you can see why I recommend you use Jekyll/GitHub Pages to keep things simple for now.

👀

**Comment by greyhound291** [comment]
Great work guys!

Don't want to be telling you guys how to do your job, but just keep in mind that there are three types of "promises" we might be dealing with:
1. Some are either yes/no like tax reforms and what not.
2. Some are more detailed.. Like arms procurement, or government tenders, or auctioning of PSUs; that have a start/middle-working-phase/end that (but cannot be quantified by percentages) can be tracked using started/work-in-progress/complete
3. Then there are things like highway projects that can be measured and so they can be maybe put in a percentage complete method

Any suggestions/additions ? I was just mentioning this because I thought now would be a more appropriate time to discuss this rather than after the mock ups are complete..

**Comment by jimaldon** [comment]
Regarding decisions regarding data presentation, we can take a lot of cues from the canadian version of the website, https://www.trudeaumetre.ca/. 

imo, it's pretty easy to understand even if you''re not canadian and/or a political layman.

**Comment by okpatil4u** [comment]
@jimdsouza  That makes sense.

**Comment by bogas04** [comment]
We've decided on Meteor + React + Bootstrap.
