### ISSUE TITLE
Programmer

### ISSUE THREAD

**Issue by okpatil4u** [reddit-india/indianelectionmeter.github.io#10]
Comment on this issue to contribute as programmer. Please mention your expertise as well. We will be posting guidelines very soon.

Join here https://iptuserbot.herokuapp.com/ at #programmers channel

**Comment by srinarasi** [comment]
I use C++ at work but know JS/HTML/CSS pretty well and a bit of Python too. But I have never worked on any complex website. Whatever I have done has only been seen by a few hundred people. So I'm open to do any kind of work.

**Comment by okpatil4u** [comment]
@srinarasi you are already in the team.

**Comment by spookyskeleton** [comment]
I'll be able to contribute to the frontend - HTML/CSS/JS and design.

**Comment by bogas04** [comment]
I would love to contribute ! I'm good with JavaScript (Frontend & NodeJS) & HTML5 and I think for now we can start with a `status.md` file as follows 

```
# done
* [date started on, date completed on] abc 

# in progress 
* [date started on] pqr

# not yet started
* xyz
```

on the github's page itself. The backend would simply [parse it](https://github.com/markdown-it/markdown-it) and use maybe ReactJS to get those nice filters for the list. Further we can use highcharts, knobjs etc to give fancy charts and stuff for proper analysis.

Since all of it depends on the `status.md` file, any other country/state can create their own fork by simply changing the name of the project and stuff in the `status.md` file. 

I have good experience with whatever I said above. More about my experience [here](http://bogas04.github.io)

**Comment by balajiramani** [comment]
I am interested.
I can do backend stuff with Django/Python, Java/Spring-Boot, AWS. I am not very proficient with frontend technologies.

**Comment by okpatil4u** [comment]
@bogas04 good suggestion. Changed readme.md. @balajiramani we are going need your expertise in backend when we start scaling it up. Welcome to the team.

**Comment by bogas04** [comment]
@okpatil4u Oh, I meant that we can use such a `status.md` for a government to parse it to JSON or something & view it on a fancy website. All the work would be to generate `status.md`s for each state and center (markdown is easier to maintain and very readable by non programmers), and the frontend can simply display charts and lists with filters around it.

**Comment by ndarville** [comment]
I can help out with front-end stuff—also most of your Jekyll needs, I imagine.

Let me know if you ever need any automated linting and stuff like that as well, as I’ve got [some experience](https://github.com/ndarville/style) with that. [LintHub](https://linthub.io/) is a really easy tool here.

**Comment by gattu94** [comment]
Know the basics of front end, can code in python, java, work on ruby on rails, django frame works, and mongodb

**Comment by okpatil4u** [comment]
@bogas04 we are running jekyll site at indianelectionmeter.in, you can see it's code on gh-pages. We are using markdown to write down each post. @ndarville should be able to help us with better formatting of jekyll site. We are still deciding the frameworks etc. You can join our discussion at https://iptuserbot.herokuapp.com.

**Comment by ashwin47** [comment]
I can help.
Rails/CSS/JS

**Comment by saurabhsjoshi** [comment]
I can make an Android app if required.

**Comment by mishravikas** [comment]
Hey! I would love to contribute to this. I have a pretty good experience in back end and can code in Python/Ruby/PHP and have worked on js frameworks like angularjs and jquery while working for Mozilla.

**Comment by nini1294** [comment]
I'm pretty good with both frontend and backend stuff. Ruby/Rails/Sinatra and the normal HTML/JS

**Comment by okpatil4u** [comment]
@ashwin47 @mishravikas @nini1294 welcome guys. Please join the slack programmer channel.

**Comment by kartikanand** [comment]
Hi! I can help with Python and JS and little bit of Sass and bootstrap!

**Comment by okpatil4u** [comment]
@kartikanand join the slack channel, welcome to the team

**Comment by karansachdeva86** [comment]
Hi, I am good with Java, Spring, Hibernate frameworks (more than 5 years ex). I have already joined Slack programmer channel.

**Comment by okpatil4u** [comment]
Thanks @karansachdeva86.

**Comment by rajnetgen** [comment]
Hi,

I have 5 years of experience in web development, PHP, HTML/CSS

**Comment by rahulkapoor90** [comment]
I am well versed with web development technologies @okpatil4u  would love to contribute to this repository.

**Comment by okpatil4u** [comment]
@rajnetgen, @rahulkapoor90 welcome. Fork this repository, and get started.

**Comment by dharmang** [comment]
I have 7.5+ years of experience in web development.
My key skills are PHP, MySQL, HTML, CSS, JavaScript, jQuery.
I have also worked with PHP frameworks like Zend Framework 1.X branch, WordPress.
I would be obliged if selected in team.

**Comment by okpatil4u** [comment]
@dharmang welcome dharmang. Please join slack programmer channel. Also fork this repo and get started.

**Comment by PCMR-FSNG** [comment]
@okpatil4u : hey there... Java & Javascript dev reporting in

**Comment by okpatil4u** [comment]
@PCMR-FSNG welcome. Join the slack channel.

**Comment by jimaldon** [comment]
Backend dev (JSPs etc)

**Comment by okpatil4u** [comment]
@jimdsouza you are already in.

**Comment by mr-karan** [comment]
I would like to contribute as well. Can help with front-end stuff (HTML,CSS,JS) and know Python as well.

**Comment by vipCodeError** [comment]
I m ready to contribute

**Comment by okpatil4u** [comment]
@123vipulj welcome, join the slack channel

**Comment by maximl337** [comment]
I would love to contribute.

**Comment by thel3l** [comment]
Et moi. Count me in.

**Comment by okpatil4u** [comment]
@maximl337, welcome, join the slack channel and fork the repo. @thel3l, welcome, you will be helping with web scrapper, I guess. Thanks for your contribution, in advance.

**Comment by okpatil4u** [comment]
We have contribution guidelines on this repo. Closing this issue.
