### ISSUE TITLE
Comment system

### ISSUE THREAD

**Issue by ndarville** [reddit-india/indianelectionmeter.github.io#18]
- [ ] Requires the creation of a page for each promise (#20)
- [x] Decide on provider

**Comment by ndarville** [comment]
## Candidates
- Disqus
- [Civil](https://www.civilcomments.com/)
- Custom made

**Comment by okpatil4u** [comment]
Let's go for discuss. It's already discussed. (not intended)

**Comment by okpatil4u** [comment]
Do we need this on 0.1 ? It was supposed to be on v2.

**Comment by bogas04** [comment]
Discuss is much better, not everyone is on facebook.

**Comment by bogas04** [comment]
About the first part of the issue, we can get the modal to open based on hashtag in url for now.

**Comment by satyarth** [comment]
Removing from 0.1 milestone based on Slack discussion.

**Comment by okpatil4u** [comment]
Added disqus, waiting for it to be added in disqus whitelisting domains.
