### ISSUE TITLE
Structure

### ISSUE THREAD

**Issue by okpatil4u** [reddit-india/indianelectionmeter.github.io#2]
Ideally it should include centre as well as state election promises as well.
We are going to need elections promises either as leaflet images or urls to confirm.
More on this later.

**Comment by greyhound291** [comment]
So this is the BJP election manifesto: http://www.bjp.org/images/pdf_2014/full_manifesto_english_07.04.2014.pdf

As a non coder, I wanted to know if there would be any way I could help...

**Comment by okpatil4u** [comment]
Yeah sure, we are going to need all those manifestos, and status updates on them, with news or assembly resolutions etc. Can you work on this ?

**Comment by greyhound291** [comment]
So I found this too: https://aapdelhidiary.wordpress.com/

They are doing a pretty good job of keeping track of the delhi govt. You think we can use their data as dummy data and design a website around it?

And yes, I will start working on that too

**Comment by okpatil4u** [comment]
This is thorough. We can do that. But we should get structure of the website fixed first. Centre should come first, followed by states. 

We need all election promises and related material first. Let's start digging.

**Comment by kjaggu** [comment]
In my opinion, let us focus on getting the BJP manifesto tracked for starters. Once we have a core team in place to monitor the development, we can branch out phase wise. Let us have a phase-wise development rather than a website with many manifestos and no tracking. We can identify people for each State who will be responsible for the task when they go live.

**Comment by srinarasi** [comment]
I agree with @kjaggu. Let's start with the Center. It should be trivial to replicate it for the states as long as we have people tracking them.

**Comment by gitrraoind** [comment]
I am an AAP member/volunteer. I was quite inspired by the canadian PM tracking stuff  and therefore I created a structure in Excel based on the AAP Delhi Manifesto. I will clean it up a bit in another 15 minutes and share it. May be we can use it as a base to create a structure or atleast get some ideas.

**Comment by okpatil4u** [comment]
@gitrraoind. Thank you. Maybe you could help us with Delhi state promise tracker. Can you take it on ?

**Comment by gitrraoind** [comment]
PFA the sheet. Please go through all the worksheets in the attachment.

Yes, I would love to collect the AAP Delhi data, if that is what you mean. However, it will be from public domain / News or AAP sources. I need ideas on how to make sure to have them verified!

[Progress Tracker v1.1.xlsx](https://github.com/reddit-india/indianelectionmeter.github.io/files/34917/Progress.Tracker.v1.1.xlsx)

**Comment by amangupta53** [comment]
What's the current status for the dynamic website?

**Comment by ghdna** [comment]
Count me in. Know extensive web development - FE and BE.

**Comment by ktn00b** [comment]
I am learning Web Dev, so I wouldnt be able to contribute directly unless there is a lack of volunteers and you are willing to go for someone who is learning+doing.

I can help with collating data, and my idea of an excel sheet for this is the following columns-

PromiseReferenceId;Promise;Promisee;LocationOfMakingPromise;Status-(UnderConsideration;U-Turn;Active;Fulfilled)

Each promise should link to its own page and also allow for moderated commenting under each promise.

**Comment by greyhound291** [comment]
@IndDev Check out the slack channel and join in on the data collection.. work on that has already started.

Slack channel: https://indianpromisetracker.slack.com
Get an invite: https://iptuserbot.herokuapp.com/

**Comment by rraoind** [comment]
I have the list of AAP Delhi's manifesto promises ready and a fair amount of data on what has been achieved! I am new to github and don't know whom to connect with to have this info uploaded on the site. Any info is appreciated!

Also, could we show the 'Days in office' rather than the 'In Power Since' date? This will create a better perspective of the situation!

**Comment by greyhound291** [comment]
@rraoind first of all, welcome! :) 

Secondly, can you dm me on slack? It's a messaging app that everyone here is using!

To join the slack channel, go here: https://indianpromisetracker.slack.com/
You will need an invite to join the channel, which you can get here: https://iptuserbot.herokuapp.com/

It's fairly easy. It wont take much time! And my username is @greyhound291 on slack

**Comment by okpatil4u** [comment]
Basic structure is fixed, let's move to specific issues of content generation and ui design now.
