### ISSUE TITLE
Detailed pages per promises

### ISSUE THREAD

**Issue by okpatil4u** [reddit-india/indianelectionmeter.github.io#20]

**Comment by satyarth** [comment]
Here's what I'm thinking we need for detailed pages:
- Clearly stated promise
- Reference to where the promise was made (link + backup)
- Current status
- Status updates (when there's major development on a promise)
- Public comments

Thoughts?

**Comment by greyhound291** [comment]
Public comments can be in v2 imo

**Comment by greyhound291** [comment]
Rest everything sounds good!

**Comment by kritinvij** [comment]
Also, add num votes received in parliament for/against the bill...? for version2

**Comment by satyarth** [comment]
Current version of the site has this as a popup; we need to:
- Have a system to assign unique IDs to each promise.
- Make separate pages for promises (so people can link to individual promises etc.).

**Comment by okpatil4u** [comment]
+1
We will need to use https://atmospherejs.com/reactrouter/react-router. Does any one have better suggestion ?

**Comment by okpatil4u** [comment]
Implemented routing, and disqus. We will add new description parameters as we go on.
