### ISSUE TITLE
Central & State Govt's Tracker

### ISSUE THREAD

**Issue by okpatil4u** [reddit-india/indianelectionmeter.github.io#21]
Both central and state governments should be tracked

**Comment by ndarville** [comment]
Can we split this up into an issue about Central + State govs? We can rename this to one of either and create a second one. Then we can fold the Central gov issue into `v0.1`. Depending on whether you consider Central=Modi or all parties.

**Comment by satyarth** [comment]
The current implementation of the website has this, closing.
