### ISSUE TITLE
New google account ?

### ISSUE THREAD

**Issue by wasim117** [reddit-india/indianelectionmeter.github.io#26]
Do we need to new google account to manage 
Analytics 
Mails
or other google services ?

**Comment by greyhound291** [comment]
I've set one up .ghound2901@gmail.com

**Comment by greyhound291** [comment]
I'll give the password to a couple of admins ... So that if anyone needs permissions and one of us is not available, the work does not stop.. Is that fine?

**Comment by greyhound291** [comment]
https://drive.google.com/folderview?id=0B_DARWg9SEb5NDBmZEhBSVdlQVE&usp=sharing

Please use the dropbox folder to access the documents and make new ones. Anyone having problems with permissions, please PM me to ghound2901@gmail.com .
If someone makes a new file, make sure its in that folder and that folder alone. Also, please check for duplicates before making new docs.

Thanks!

**Comment by kritinvij** [comment]
When greyhound above says dropbox folder, he/she means the gdrive folder as linked.

Can someone close this issue?
