### ISSUE TITLE
Slack team

### ISSUE THREAD

**Issue by srinarasi** [reddit-india/indianelectionmeter.github.io#3]
I created a slack team for the project as it's a much better tool for collaboration.
I named it Indian Promise Tracker as thought it conveys the intent more accurately.
https://indianpromisetracker.slack.com

Use this link to join: https://iptuserbot.herokuapp.com/

**Comment by xero08** [comment]
Count me in if appropriate. I can contribute with the front end and anything with PHP at backend.

**Comment by okpatil4u** [comment]
Front end sounds good @anuvab1911. We won't be making it dynamic, I guess. Static site makes sense. We would be showing information stored in json files. That should get us started. If we need, we can add more functionalities later. What do you think @srinarasi  ?

**Comment by okpatil4u** [comment]
@srinarasi, it seems you need to send invite for this project on slack. Let's make these discussions public on github for now. We can go for slack anytime later.

**Comment by wasim117** [comment]
Invite me

**Comment by avinassh** [comment]
@okpatil4u @srinarasi you can use [Slackipy](https://github.com/avinassh/slackipy) if you want to automate the invite process. I am the author, let me know if you need any help.

**Comment by itsprdp** [comment]
+1 Full Stack dev here

**Comment by okpatil4u** [comment]
Yay, @avinassh is here, are you going to make us rockstars as well ? ;-)
Can you start a heroku dyno with slackpy ? You could co-ordinate with @srinarasi for this one.

**Comment by avinassh** [comment]
ha ha. 

I need a slack admin API key to create a dyne on Heroku. Its better you or @srinarasi creates it.

**Comment by okpatil4u** [comment]
@srinarasi, can you pm @avinassh the api key ? Or @avinassh, would it be better if you create and maintain it yourself ?

**Comment by avinassh** [comment]
sure, I don't mind. Give me an API key created by an admin user, not owner. @srinarasi has to create a new user, give him admin privileges and generate an API key.

**Comment by kjaggu** [comment]
I would like to contribute from a content point of view, which includes creating content for the front-end, editing, etc. Can also help in finalising the look for the front-end. A friend and I have discussed the development in detail in the past, and we would be keen to share and get your views on the process of tracking.

**Comment by anirudhvarma12** [comment]
I would also like to contribute. Can do front-end work. HTML+CSS but a bit of JS too.

**Comment by okpatil4u** [comment]
@kjaggu can you co-ordinate with @greyhound291 for content generation. Please create a seperate thread for each one.

**Comment by kjaggu** [comment]
@okpatil4u Thanks. I am new to Github. By a seperate thread, do you mean a new 'issue'?

**Comment by avinassh** [comment]
@kjaggu yes

**Comment by code-haven** [comment]
Fullstack developer here - I would like to be a part of this :+1:

**Comment by okpatil4u** [comment]
@code-haven welcome. We would be working on frontend and content generation for now.

**Comment by srinarasi** [comment]
I've automated the user registration. Please use this link to register. https://iptuserbot.herokuapp.com/

Thanks to @avinassh making the process a breeze. Excellent little utility.

**Comment by kritinvij** [comment]
Hey! I am here. Seems nice to see you guys make so much progress from the initial post & discussion that we made!
Can you invite me for Slack at kritinv@uw.edu

**Comment by greyhound291** [comment]
Use this @kritinvij  : https://iptuserbot.herokuapp.com/

**Comment by kritinvij** [comment]
Thanks greyhound!

**Comment by okpatil4u** [comment]
Slack forum is online, closing this issue.
