### ISSUE TITLE
Content Generator

### ISSUE THREAD

**Issue by itsprdp** [reddit-india/indianelectionmeter.github.io#35]
Data collection made easy. Once we have the data in the DB we can always export it to CSV, JSON, YAML or whatever possible format.

I was thinking to scaffold the application with Rails and host it on heroku for now. We need to come up with the required fields in the form.

**Comment by satyarth** [comment]
@okpatil4u is working on this ATM, let's see what he comes up with.

**Comment by okpatil4u** [comment]
Content generator is online and functional
