### ISSUE TITLE
Creating tagline for the site

### ISSUE THREAD

**Issue by okpatil4u** [reddit-india/indianelectionmeter.github.io#39]
> > We are kicking off Indian Election Meter. This site is inspired by a post at /r/india comparing a canadian site to indian election promise tracker scenario. We are just getting started. If you are a programmer or a content writer, file your feature requests at Our GitHub Repository.

This is the current tagline. We need a new one.

**Comment by satyarth** [comment]
"Holding our leaders accountable for their promises"? Short and sweet.

**Comment by greyhound291** [comment]
indianelectionmeter.in: "Accountability through/via/supported by/backed by data"

We can use another word instead of "through"

**Comment by okpatil4u** [comment]
It should be simpler. Easy to understand. I am going with @satyarth 's suggestion for now, will change when need.

**Comment by satyarth** [comment]
I like @greyhound291's suggestion too. Catchy!

**Comment by satyarth** [comment]
Closing for now. Can update later pending further discussion.
