### ISSUE TITLE
License of BJP Manifesto

### ISSUE THREAD

**Issue by avinassh** [reddit-india/indianelectionmeter.github.io#4]
I am not sure we can add BJP Manifesto to the repo. What is the license of that document?

**Comment by kjaggu** [comment]
I don't think we should have an issue with that. It is a public document. If there is an issue, we can give a direct link to their website from [here](http://www.bjp.org/manifesto2014).

**Comment by avinassh** [comment]
> I don't think we should have an issue with that. It is a public document.

Thats not how it works. If a document does not come with license or copyright notice, then it does not mean we have rights to distribute.

**Comment by okpatil4u** [comment]
@avinassh adding links would not make sense, they can always delete the source, adding document will give it validity. Let's not worry about it right now, they seem to public documents for time being.

**Comment by kjaggu** [comment]
@avinassh What I meant was the document is supposed to be in the public domain. We are not going to redistribute the document for commercial purposes. Moreover, the document is going to be a reference point. The various promises will have to be broken down into sections and sub-sections. I am opening a new thread detailing the content plan.

**Comment by avinassh** [comment]
> Let's not worry about it right now, they seem to public documents for time being.
> 
> What I meant was the document is supposed to be in the public domain.

Why are you calling it `public document`? Is it because since it is available on Internet or have they released it under Public Domain?

> We are not going to redistribute the document for commercial purposes. 

It doesn't matter, whether you use it for commercial purposes or not.

**Comment by okpatil4u** [comment]
@avinassh I agree, but we will have to build it on something. These manifesto make solid foundation. Do you have any alternative solution ?

**Comment by avinassh** [comment]
Yes :) 
1. Give link to original document
2. Keep a local copy 
3. Keep a copy on Dropbox ;)
4. Use https://archive.is 

Basically do not distribute documents/code on which you do not have rights to do so, with this repo.

**Comment by satyarth** [comment]
I agree with @avinassh. Link to the original document works fine, and if we're worried about it being altered could post a hash of the version we're referring to.

**Comment by okpatil4u** [comment]
I agree as well, closing off this issue.

**Comment by okpatil4u** [comment]
@avinassh archive.is is not uploading big files. We will use archive.org. People have already archived all these documents way back when they were uploaded.
