### ISSUE TITLE
Categories and Subcategories

### ISSUE THREAD

**Issue by davistom** [reddit-india/indianelectionmeter.github.io#41]
About 15 categories will be good. 

Currently I've the following based on [BJP full manifesto](https://docs.google.com/spreadsheets/d/1cFQwHs3AgyPv69K4xUuIAt-RuvyYwVz6Szz0VmnVAW8/edit#gid=0): 
- . Agriculture
- . Business
- . Corruption
  - a. Black Money
  - b. Reforms
- . Economy
  - a. Price Rise
- . Education
- . Employment
- . Empowerment
  - a. Children
  - b. Minorities
  - c. Senior citizens
  - d. Specially abled
  - e. Women
  - f. Youth
- . Energy
- . Environment
- . Healthcare
- . Infrastructure
  - a. Railway
  - b. Roads
  - c. Water transportation
- . Reforms
  - a. Administrative
  - b. Electoral
  - c. Judicial
  - d. Police
  - e. Political
  - f.  Social
- . Regional
  - a. Jammu & Kashmir
  - b. Northeast
- . Security
  - a. Defense Production
  - b. External Security
  - c. Internal Security
- . Sports 
- . Technology
- . Tourism

If more categories are needed or some of the above can be put together as sub-categories in a particular category, please contribute. 

Update1: Updated with first two comments.

**Comment by greyhound291** [comment]
Railways and Highways? Under infrastructure?

**Comment by kritinvij** [comment]
Initially someone had categories as listed as follows..
Can you check if all of them are present?
Administration
Agriculture
Corruption
Defense
Economy
Energy
Environment
Healthcare
Human Resource Development
Industry
Infrastructure
Internet & Telecommunications
Railways
Social Justice
Tourism
Women Empowerment
YouthEducation
Law/Judicial
Manufacturing

**Comment by greyhound291** [comment]
Please add/remove/sort categories and sub categories here:

https://docs.google.com/spreadsheets/d/1yK1KDcJsqINRueoX2Zkubmx2dheIlt1LogU6xjwwpTY/edit#gid=0

Also, try and stick to these categories while transcribing manifestos of state governments. That way, there will be uniformity across the website.

**Comment by greyhound291** [comment]
@satyarth Can this issue be considered closed? If someone has anything they want to say, they can remake the issue.

**Comment by satyarth** [comment]
@greyhound291 cool, closing for now.
