### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by ndarville** [reddit-india/indianelectionmeter.github.io#44]
The `gh-pages` branch has both an MIT and Apache license in it.

I assume the idea is to make openly available data for everyone to use. The question that remains is what license we should use for
- [ ] The data
- [x] The website source code

**Comment by okpatil4u** [comment]
What do you suggest ?

**Comment by ndarville** [comment]
The MIT License seems like the best bet for the source code:

![licenses](https://cloud.githubusercontent.com/assets/198682/11213571/f7601adc-8d3c-11e5-90cd-a220e4b560ad.PNG)
- http://choosealicense.com/licenses/

GPL is also an option, if you want to demand that people disclose their source—and don’t sublicense the code.

Copyrighting data from publicly available information is hard, but I mainly encourage licenses so people don’t get scared of using the code out of fear that it’s legally tricky.

**Comment by satyarth** [comment]
:+1: for MIT

**Comment by itsprdp** [comment]
+1 for MIT

**Comment by ghost** [comment]
:+1:  for GPL

**Comment by satyarth** [comment]
MIT seems favored, let's go with it for now. Changed in 3620eb1b5df5941595cb1d7c735d30179c8da068 .
