### ISSUE TITLE
Augment Table component to have `Remind` column, add same to showModal

### ISSUE THREAD

**Issue by bogas04** [reddit-india/indianelectionmeter.github.io#45]
Based on https://github.com/reddit-india/indianelectionmeter.github.io/issues/24
- Update `rows` in `render` of `<Table />` Component to have `Remind` column which help user tweet/fb post the party's account about the same promise.
- Add same capabilities in the `showModal` function. 

Very easy to do, shouldn't take much time.

**Comment by okpatil4u** [comment]
Not relevant in new design.
