### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by davistom** [reddit-india/indianelectionmeter.github.io#47]
**Programmmer**
Q: What technologies are using?
A: Front-end - react. Template for content generators - meteor 
Q: I saw indiantracker.in, why are we not using it? 
A: We can't because The person who made it using his own framework. He does not have the appropriate documentation for it and so it might be a problem at a later stage. 

**Content Writer**
Q: I’m not a coder, how can I contribute? 
A: You can pick one of the [promise](https://docs.google.com/spreadsheets/d/1uJHLsrWgvPG-3ARHQJMoCrxnbACFq6B0Klz8SPHREuk/) we have listed or promise you find yourself and start collecting content. Once the website is up, you will have a form to enter the data you collected.

**Comment by satyarth** [comment]
Aiming to cover in the readme, closing issue.
