### ISSUE TITLE
Information on States

### ISSUE THREAD

**Issue by okpatil4u** [reddit-india/indianelectionmeter.github.io#49]
Can anyone collect following data for all the states in India ?
- Name
- Ruling Party
- In Power Since
- Chief Minister
- Remaining Period

@satyarth Please assign it to @davistom or @greyhound291

**Comment by greyhound291** [comment]
@okpatil4u : https://docs.google.com/spreadsheets/d/10si9WR_lQKtgrVLCH8Uej7zvTe8oLF45zSgYZ_lkJJU/edit?usp=sharing

"Remaining period in office" I'll fill later. But you have something to work with today!

**Comment by satyarth** [comment]
Waiting on @greyhound291 to be added to the github org to formally 'assign' this issue.

**Comment by okpatil4u** [comment]
@greyhound291 I need images as well, can you fill in the urls ?

**Comment by greyhound291** [comment]
Images of states? Or CMs?

**Comment by okpatil4u** [comment]
CM's

**Comment by greyhound291** [comment]
Doc is complete. Issue can be closed.

**Comment by satyarth** [comment]
Thanks @greyhound291! Closing.
