### ISSUE TITLE
Data format 

### ISSUE THREAD

**Issue by greyhound291** [reddit-india/indianelectionmeter.github.io#5]
How do you devs want the data?

I was starting to go through the BJP manifesto right now, maybe just make a list of promises that can be followed up on later by anyone interested in contributing..

Is excel going to be fine? Google Sheets? or is there anything else you devs have in mind that might be noob friendly and easier to incorporate into the website?

**Comment by okpatil4u** [comment]
I don't think that google sheets or excel could work that easily. We are going to need yaml or json format to get started. They are simple file formats. You can use text editors like sublime-text to get started with them. 

Also you have to learn git versioning. Here is a simple tutorial.
https://try.github.io/levels/1/challenges/1

You fork the repository. Clone forked repository on your computer. Make changes. Commit them. Push them online. And create a pull request to the main repository. 

It's seems complicated here. But it's quite easy, once you start. Ping me if you need any help.

**Comment by avinassh** [comment]
@okpatil4u I would suggest a Google Form to take input. It can be easily exported to JSON.

**Comment by okpatil4u** [comment]
Google form can be edited online if it's a public document. We can track changes better if it's a written and committed document by a known user. Short term google forms would work, but for long term we have to track and validate changes. That is going to be headache.

**Comment by avinassh** [comment]
^I agree with those issues.

**Comment by srinarasi** [comment]
To be successful, I feel that people who don't know anything technical should be able to contribute. I don't think only programmers can keep the data upto date or verify all the changes. Can't we use Google Forms and still be able to do version control and validation? We can automate all of these right?

**Comment by kjaggu** [comment]
I agree. Ideally, a basic CMS should be helpful for non-technical users like me.

**Comment by avinassh** [comment]
or we will use MediaWiki, what do you guys think?

**Comment by okpatil4u** [comment]
I have started a simple Jekyll based on gh-pages branch. I have bought indianelectionmeter.in and redirected the traffic to indianelectionmeter.github.io.
You are right. We should start with google forms. We will migrate to code commits when we have definite structure.

**Comment by okpatil4u** [comment]
Default data format is json now, closing this issue.
