### ISSUE TITLE
Trimming down categories

### ISSUE THREAD

**Issue by okpatil4u** [reddit-india/indianelectionmeter.github.io#50]
Currently we have 67 categories
[
    "Price Rise ",
    "Employment and Entrepreneurship ",
    "Corruption",
    "Black Money ",
    "Poor Delivery ",
    "Credibility Crisis ",
    "Decision and Policy Paralysis ",
    "Centre-State Relations ",
    "Northeast ",
    "Jammu and Kashmir ",
    "Decentralization and People's Participation ",
    "Open Government and Accountable Administration ",
    "E-Governance: Easy, Efficient and Effective ",
    "Institutional Reform - Administrative ",
    "Institutional Reform - Judicial ",
    "Institutional Reform - Police ",
    "Electoral",
    "Poor and Marginalized - Bridge the Gap ",
    "Food Security ",
    "Social Justice and Empowerment ",
    "Minorities - Equal Opportunity ",
    "Rural Areas - High Priority ",
    "Neo-Middle Class - Meet their Aspirations ",
    "Urban Areas - High Growth Centres ",
    "Social Security - Children ",
    "Social Security - Specially Abled ",
    "Social Security - Senior Citizens ",
    "Youth - Making India Unstoppable ",
    "Promotion of Sports ",
    "Women - The Nation Builder ",
    "School Education ",
    "Higher and Professional Education ",
    "Vocational Training ",
    "Skills - Focusing on Productivity and Employability ",
    "Health Services ",
    "Economic Revival ",
    "Taxation ",
    "Agriculture ",
    "Industry ",
    "Manufacturing ",
    "Cooperative Sector ",
    "Handicrafts ",
    "MSMEs ",
    "Business and Trade ",
    "Artisans ",
    "Tourism ",
    "Labour Force ",
    "Housing ",
    "Physical Infrastructure ",
    "Next Generation Infrastructure ",
    "Transport",
    "Railway ",
    "Water ",
    "Energy ",
    "Science and Technology ",
    "Flora, Fauna and Environment ",
    "Himalayas ",
    "Natural & National Resources ",
    "Internal Security ",
    "External Security ",
    "Defence Production ",
    "Independent Strategic Nuclear Programme ",
    "Foreign Relations ",
    "Cultural Heritage ",
    "Seemandhra and Telangana ",
    "Uniform Civil Code ",
    "Price Rise"
]

Can we trim it down ? 
@satyarth

**Comment by greyhound291** [comment]
Already an issue here: https://github.com/reddit-india/indianelectionmeter.github.io/issues/41

@davistom has trimmed them down to 15 broad categories and I think everything here can be put as sub categories under those

**Comment by greyhound291** [comment]
Why not try and work with them here and fit them into as little categories as possible?

https://docs.google.com/spreadsheets/d/1yK1KDcJsqINRueoX2Zkubmx2dheIlt1LogU6xjwwpTY/edit#gid=0
