### ISSUE TITLE
Need for having contributing guidelines for newcomers

### ISSUE THREAD

**Issue by greyhound291** [reddit-india/indianelectionmeter.github.io#51]
https://github.com/blog/1184-contributing-guidelines

This is supposed to explain the following:
1. How to get into the slack channel
2. How to use the docs
3. How to use the common document folders:
   - To use their email ID and not log in as anon. to enable tracking of changes  
   - To NOT make new doc sheets on their own drive and share it on the folder
   - To MAKE All documents in the common folder
   - All excel files need to have 2 sheets (1st one is for maintenance purposes where the sources for data, people working on the sheet, and any other misc. notes can be made for the reference of others, _AND if the sheet is Complete or a Work in progress_, 2nd sheet with all the main data)
   - To follow a fixed format while adding, removing data.
   - If the format does not exist, then get hold of a dev working in the relevant area and make the doc. as per his requirements
4. Explanation of the stack currently in use
5. _Any guidelines from devs_
6. FAQ's
7. Usernames of relevant people heading the different kinds of jobs

**Comment by satyarth** [comment]
Working on this.

**Comment by satyarth** [comment]
Started this in b7e51cc9049d50867b52e87efb35950e4f77e2a4. I'm not too clear on how a content writer can get started ATM, @greyhound291 or @davistom could you handle that?

**Comment by satyarth** [comment]
Updated in 307a68d8e3b7d0aec5a596c5c71a35095ae10a9c. Closing for now, feel free to comment if any updates are required.

**Comment by okpatil4u** [comment]
@satyarth should we have it in readme.md ? I don't want them clicking another link

**Comment by satyarth** [comment]
I think it makes sense to separate information that someone interested in the project would want to know from information specifically for contributors. Although theres not much in the readme ATM, that will change as we continue to grow and it would get harder to get an overview at a glance.

Can make the link to the contributing doc more prominent if that's a suitable compromise?

**Comment by ndarville** [comment]
CONTRIBUTING.md is mainly to generate the info alert for when people submit issues and PRs.
