### ISSUE TITLE
Web Domain and Hosting

### ISSUE THREAD

**Issue by greyhound291** [reddit-india/indianelectionmeter.github.io#7]
I know a company based in delhi that provides hosting solutions.. Our personal company website is hosted with them and he is very cheap when compared to options like godaddy and the works. If anyone is interested i can share the details here, or anywhere else, and maybe someone with a technical background can follow up with him

**Comment by okpatil4u** [comment]
I have bought indianelectionmeter.in. I will redirect the traffic at indianelectionmeter.github.io. So we can start with this. We can discuss other options later on. What do you say ?

**Comment by greyhound291** [comment]
cool so thats sorted then
