### ISSUE TITLE
Content Writer

### ISSUE THREAD

**Issue by okpatil4u** [reddit-india/indianelectionmeter.github.io#9]
Comment on this issue if you want to contribute as content writers. We will set up guidelines very soon.

Join the discussion at https://iptuserbot.herokuapp.com/ at #contentwriters

**Comment by lunaroyster** [comment]
Definitely interested at the prospect of creating unique and engaging content. 

It would be a pleasure to collaborate on a project with other highly skilled individuals to bring government accountability to the table in a country where impotent office holders often deceive voters by frequently engaging in misinformation, spreading falsehoods and by operating against the very force that accorded them the powers.
TL;DR: I'm in.

**Comment by okpatil4u** [comment]
@lunaroyster lol, welcome

**Comment by kjaggu** [comment]
Count me in.

---

Not to decide is to decide.

**Comment by greyhound291** [comment]
Content writer checking in!

**Comment by gattu94** [comment]
I can write too!!

**Comment by sarcasticprani** [comment]
Count me in! Can't code but can work on data collection,analysis and content creation!!

**Comment by okpatil4u** [comment]
@sarcasticprani we need animals like you. Can you join slack, and visit the govtofindia channel ? We need to form basic documents to get started with. Link is posted in comment above.

**Comment by okpatil4u** [comment]
We have contribution guidelines on this repo. Closing this issue.
